$schemaver: 2.0
deployables:
  - name: byu-ws-sdk-python
    type: Library
    aliases:
    short_description: A Python SDK for calling BYU REST web services.
    assignment_group: gro:AD-Student Life Applications
    notes:
    maintained_by:
      - ndpete
      - brettbeatty
    developed_by_byu: true
    ddd:
        business_domain:
        ubiquitous_language_url:
        context_map_url:
    links:
        system_documentation_url:
        source_repo_url: https://github.com/test-ndpete-org/byu-ws-sdk-python
        swagger_urls:
    microservice: false
    technologies_used:
      - Python
    stages:
        production:
            urls:
                product_page:
                physical_url:
                virtual_url:
            hosting_location:
            aws_account:
            relationships:
                depends_on:
                    db_read_write:
                    db_read_only:
                    software:
                supports:
                    software:
                    service:
                reverse_proxy:
                runs_on:
                    server_cluster:
                    virtual_server:
                    rack_server:
                    blade_server:
    tags:
        data-sensitivity: confidential
        env: prd
        app: byu-ws-sdk-python
        team: gro:AD-Student Life Applications
    federation_json_url: https://raw.githubusercontent.com/test-ndpete-org/byu-ws-sdk-python/master/.repo-meta.yml

